service: club-tweeter

frameworkVersion: "3"

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  region: eu-west-2
  environment:
    APP: FIX_TWEETER

package:
  patterns:
    - "!./**"
    - ./bin/**

functions:
  sosemtcc_fixtures:
    handler: bin/clubTweeter
    events:
      - schedule: cron(0 9 * * ? *)
    memorySize: 128
